# Generated by Django 4.2.2 on 2023-06-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.CharField(max_length=250),
        ),
    ]
