# Generated by Django 4.2.2 on 2023-06-28 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participant_details_participant_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='signed',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
