# Generated by Django 4.2.2 on 2023-06-22 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_report_delete_image_alter_event_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
    ]
