# Generated by Django 4.2.2 on 2023-06-28 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_cgpa'),
        ('events', '0003_participant_signed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='details',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='proof',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='signed',
        ),
        migrations.AddField(
            model_name='event',
            name='signed',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.club'),
        ),
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event'),
        ),
    ]
