# Generated by Django 4.2.2 on 2023-06-26 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('details', models.CharField(max_length=500)),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='studentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.student')),
            ],
            options={
                'unique_together': {('project', 'student')},
            },
        ),
    ]
