# Generated by Django 4.2.2 on 2023-07-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_approval_project_category_project_completion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
