# Generated by Django 4.2.2 on 2023-07-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_crypto'),
        ('project', '0003_project_link_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.department'),
        ),
    ]
