# Generated by Django 4.2.2 on 2023-07-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='usershash',
            new_name='current_hash',
        ),
        migrations.AddField(
            model_name='block',
            name='users_hash',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
