# Generated by Django 4.2.2 on 2023-07-05 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendacerequest',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendacerequest',
            name='signed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
