# Generated by Django 4.2.2 on 2023-06-28 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_fam_faculty_alter_fam_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='signed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
