COIN1 = "$GOLD"
COIN2 = "$SILVER"
FILE1 = "log/chain1.pickle"
FILE2 = "log/chain2.pickle"
RATIO = 2

INITIAL_TOKEN_COIN1 = 100
NEW_TOKEN_COUNT_COIN1 = 10

INITIAL_TOKEN_COIN2 = 100
NEW_TOKEN_COUNT_COIN2 = 10

SUCCESS = {"Ok":"success"} 
FAILURE = {"Ok":"error"}