# Generated by Django 4.2.2 on 2023-06-14 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('srn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.faculty')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
